import { AppHeader } from '@/components/shared/app-header'
import { AppFooter } from '@/components/shared/app-footer'

export const metadata = {
  title: 'Terms of Service',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <AppHeader />

      <main className="flex-1 px-4 sm:px-6 lg:px-8 py-12">
        <div className="max-w-2xl mx-auto space-y-8">
          <div>
            <h1 className="text-2xl font-semibold text-foreground">
              Terms of Service
            </h1>
            <p className="mt-2 text-sm text-muted-foreground">
              Last updated: February 2026
            </p>
          </div>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">
              1. Overview
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              This application is an internal tool built and maintained by a
              member of the PrimeMover team. It is intended exclusively for use
              by authorized PrimeMover team members in the course of their work.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">
              2. Access &amp; Authorization
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Access to this tool is granted through PrimeMover&apos;s internal
              authentication system. You must be an active team member with valid
              credentials to use this application. Do not share your access
              credentials with anyone outside the organization.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">
              3. Acceptable Use
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              This tool should be used solely for its intended purpose within
              PrimeMover operations. You agree not to misuse the application,
              attempt to compromise its security, or use it for purposes outside
              the scope of your role.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">
              4. Data &amp; Content
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Any data entered into or generated by this tool is the property of
              Prime Mover LLC. Content should be treated as confidential internal
              information unless otherwise specified.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">
              5. No Warranty
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              This tool is provided as-is for internal use. While we strive to
              keep it reliable and available, no guarantees are made regarding
              uptime, accuracy, or fitness for a particular purpose.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-foreground">
              6. Changes
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              These terms may be updated at any time. Continued use of the
              application constitutes acceptance of any changes.
            </p>
          </section>
        </div>
      </main>

      <AppFooter />
    </div>
  )
}
